[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "voter_participation_extractor_portland_maine"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.9"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/voter_participation_extractor_portland" }
dependencies = [
    "pandas==2.2.0",
    "pypdfium2==4.26.0"
]

[project.optional-dependencies]
dev = [
    "pre-commit==3.6.0",
    "ruff==0.1.14"
]
github-actions = [
    "ruff==0.1.14",
    "ydiff==1.2"
]
